server:
  port: 8004
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/internetmemory?serverTimezone=UTC
    username: root
    password: ACDCacdc120
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    sentinel:
      transport:
        port: 9998
        dashboard: localhost:8080
feign:
  sentinel:
    enabled: true
snowflake:
  datacenterId: 2
  workId: 1
mybatis-plus:
  mapper-locations: classpath:mapper/*
  global-config:
    db-config:
      logic-delete-field: isBlack
      logic-delete-value: 1
      logic-not-delete-value: 0
swagger:
  base-package: com.gulincover.other
  title: "other api"
  version: "1.0.0"
  description: "other api development"
  group-name: "other api"
